### ISSUE TITLE
Spaces are incorrectly stripped

### ISSUE THREAD

**Issue by pfrazee** [shama/bel#72]
https://github.com/shama/bel/commit/253d352f47e6fd09c69adeabf16a9a649a98133b This commit is pulling out spaces that we need.

![screen shot 2017-05-10 at 2 34 59 pm](https://cloud.githubusercontent.com/assets/1270099/25917594/3d0ef8be-358e-11e7-865c-adc95b8fd91c.png)

There are a couple of examples in there; ie '1addition' should be '1 addition'.

**Comment by mantoni** [comment]
This was introduced in #68 and there is a related issue in yo-yoify: https://github.com/shama/yo-yoify/issues/48

**Comment by yoshuawuyts** [comment]
uh oh, this is no good - back from holiday tomorrow - will take a look into fixing this then C: - sorry for the inconvenience!

**Comment by mantoni** [comment]
No worries. I just pinned the version number for now.

**Comment by kemitchell** [comment]
This one got me, too.  I was able to work around it with explicit `document.createTextNode(' ')` between `<span>` templates.

No pressure on this at all.  Really appreciate everyone's work.  I figure @yoshuawuyts has the Deep Knowledge on this and where to go with it, since the commit was his.  But in case I'm wrong, just let me know.  I can try and cook up a patch.
